# Generated by Django 5.2.5 on 2025-08-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
