# Generated by Django 5.2.5 on 2025-08-28 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(max_length=255)),
                ("month", models.CharField(max_length=255)),
                ("duration", models.IntegerField()),
                ("num_people", models.CharField(max_length=255)),
                ("holiday_type", models.CharField(max_length=255)),
                ("budget_type", models.CharField(max_length=255)),
                ("comments", models.TextField(blank=True, null=True)),
                ("itinerary", models.TextField(blank=True, null=True)),
                ("activity_suggestions", models.TextField(blank=True, null=True)),
                ("useful_links", models.JSONField(blank=True, null=True)),
                ("weather_forecast", models.TextField(blank=True, null=True)),
                ("packing_list", models.TextField(blank=True, null=True)),
                ("food_culture_info", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="planner.trip"
                    ),
                ),
            ],
        ),
    ]
