# Generated by Django 5.2.5 on 2025-08-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="accommodation_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
