# Generated by Django 5.2.5 on 2025-08-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_trip_accommodation_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="expense_breakdown",
            field=models.TextField(blank=True, null=True),
        ),
    ]
