# Generated by Django 5.2.5 on 2025-08-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_trip_expense_breakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="complete_trip_plan",
            field=models.TextField(blank=True, null=True),
        ),
    ]
