# Generated by Django 5.2.5 on 2025-08-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_trip_complete_trip_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="activity_suggestions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="food_culture_info",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="weather_forecast",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
